---
title: "Ecología"
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: true
      smooth_scroll: true
---

# **Detección de basura con inteligencia artificial**

El crecimiento de la población urbana y la migración de la población rural a los núcleos urbanos en México y Latinoamérica, han sido factores importantes para la expansión de las ciudades durante el siglo pasado. Con el desarrollo de proyectos inmobiliarios en lugares centrales de mega-ciudades durante los últimos 25 años, el valor creciente de la tierra y los procesos de reurbanización indujeron a los habitantes de bajos ingresos a trasladarse a la periferia urbana (Couturier y Huerta, 2020).
  
  
### **¿Cuáles fueron los resultados?** 

Se define Inteligencia Artificial como el conjunto de algoritmos y herramientas planteadas con el propósito de crear máquinas que presenten las mismas capacidades que el ser humano, cómo automatizar la toma de decisiones, la resolución de problemas y la capacidad de aprendizaje. 


Sus resultados los llevaron a hacer algunas recomendaciones hortícolas. Se encontraron con que la borraja, la lavanda, la mejorana y las variedades abiertas de dalias eran muy buenas para los insectos.

- Los coloridos alhelíes perennes también resultaron muy atractivos para los polinizadores. Sin embargo, el popular geranio no es del gusto de los estos insectos.

- Las mejoranas fueron las más “todo terreno”, según los investigadores, las que atrajeron abejas, abejorros, sírfidos y mariposas.

- Mientras las borrajas fueron las mejores para las abejas, las dalias abiertas y lavandas fueron las más atractivas para los abejorros.